In [251]:
import pandas as pd
import numpy as np

In [252]:
nc_output= pd.read_csv("data/배추_생산량.csv", encoding="utf-8")
nc_output

,시도별,2000,2000.1,2000.2,2000.3,2000.4,2000.5,2000.6,2000.7,2000.8,...,2021.2,2021.3,2021.4,2021.5,2021.6,2021.7,2021.8,2021.9,2021.10,2021.11
0,품목별,일반봄배추:면적 (ha),10a당 생산량 (kg),생산량 (톤),고랭지배추:면적 (ha),10a당 생산량 (kg),생산량 (톤),노지가을배추:면적 (ha),10a당 생산량 (kg),생산량 (톤),...,생산량 (톤),고랭지배추:면적 (ha),10a당 생산량 (kg),생산량 (톤),노지가을배추:면적 (ha),10a당 생산량 (kg),생산량 (톤),노지겨울배추:면적 (ha),10a당 생산량 (kg),생산량 (톤)
1,서울특별시,72,3695,2660,0,0,0,23,10152,2335,...,228,0,0,0,6,12793,771,0,0,0
2,부산광역시,403,4446,17917,0,0,0,324,10835,35105,...,259,0,0,0,36,11239,4017,0,0,0
3,대구광역시,177,4799,8494,0,0,0,139,10657,14813,...,1343,0,0,0,68,7248,4895,0,0,0
4,인천광역시,107,4316,4618,0,0,0,166,9907,16446,...,378,0,0,0,138,9664,13333,0,0,0
5,광주광역시,178,5090,9060,0,0,0,195,10437,20352,...,792,0,0,0,43,9772,4162,0,0,0
6,대전광역시,6,4696,282,0,0,0,99,9312,9219,...,154,0,0,0,59,8143,4821,0,0,0
7,울산광역시,61,4410,2690,0,0,0,91,10382,9448,...,503,0,0,0,85,7767,6577,0,0,0
8,세종특별자치시,-,-,-,-,-,-,-,-,-,...,487,0,0,0,50,9598,4839,0,0,0
9,경기도,1331,3903,51949,0,0,0,2458,8778,215763,...,13434,0,0,0,1185,8986,106510,0,0,0
10,강원도,2147,4081,87619,7461,3770,281280,1283,7545,96802,...,49258,5143,4470,229873,1445,7906,114251,0,0,0
11,충청북도,2561,5308,135938,81,3905,3163,1346,8926,120144,...,30787,0,0,0,2304,7321,168678,0,0,0
12,충청남도,810,4011,32489,0,0,0,2819,10624,299491,...,17111,0,0,0,1211,8676,105059,0,0,0
13,전라북도,713,4272,30459,1604,3660,58706,2060,11817,243430,...,24901,89,3214,2868,1296,9304,120590,0,0,0
14,전라남도,6320,5120,323584,0,0,0,2540,10061,255549,...,72993,0,0,0,3226,9933,320451,3236,6931,224283
15,경상북도,2816,4109,115709,584,3942,23021,1528,9460,144549,...,60477,312,3850,11997,1712,7256,124232,0,0,0
16,경상남도,707,3589,25374,476,3896,18545,1096,10141,111145,...,7273,8,4741,380,477,9190,43845,0,0,0
17,제주도,499,3731,18618,0,0,0,246,8912,21924,...,4656,0,0,0,4,9933,434,38,6029,2301

In [253]:
# 품목별로 추출
type= nc_output[nc_output["시도별"]=="품목별"]

In [254]:
# city 배열 생성
city = ["서울특별시", "부산광역시", "대구광역시", "인천광역시", "광주광역시", "대전광역시", "울산광역시", "세종특별자치시", "경기도", "강원도", "충청북도", "충청남도", "전라북도", "전라남도", "경상북도", "경상남도", "제주도"]
city_list= ["seoul", "busan", "daegu", "incheon", "gwangju", "daejeon", "ulsan", "sejong", "gyeonggi", "gangwon", "chungbuk", "chungnam", "jeonbuk", "jeonnam", "gyeongbuk", "gyeongnam", "jeju"]

In [255]:
# city 배열과 city_list 배열을 이용하여 city별로 추출
for i in range(len(city)):
    globals()[city_list[i]] = nc_output[nc_output["시도별"]==city[i]]

In [256]:
# type과  시도별로 합치기
for i in range(len(city)):
    globals()[city_list[i]] = pd.merge(type, globals()[city_list[i]], how="outer")

In [257]:
yr_list= np.arange(2000, 2022)
detail = [".1", ".2", ".3", ".4", ".5", ".6", ".7", ".8", ".9", ".10", ".11"]
spring= []
summer= []
fall= []
winter= []

for yr in yr_list:
    spring.append(str(yr))
    for i in range(0,2):
        val= str(yr) + detail[i]
        spring.append(val)
    for i in range(2,5):
        val= str(yr) + detail[i]
        summer.append(val)
    for i in range(5,8):
        val= str(yr) + detail[i]
        fall.append(val)
    for i in range(8,11):
        val= str(yr) + detail[i]
        winter.append(val)
print(spring)

# season 배열 생성
season = ["spring", "summer", "fall", "winter"]
season_list= [spring, summer, fall, winter]

['2000', '2000.1', '2000.2', '2001', '2001.1', '2001.2', '2002', '2002.1', '2002.2', '2003', '2003.1', '2003.2', '2004', '2004.1', '2004.2', '2005', '2005.1', '2005.2', '2006', '2006.1', '2006.2', '2007', '2007.1', '2007.2', '2008', '2008.1', '2008.2', '2009', '2009.1', '2009.2', '2010', '2010.1', '2010.2', '2011', '2011.1', '2011.2', '2012', '2012.1', '2012.2', '2013', '2013.1', '2013.2', '2014', '2014.1', '2014.2', '2015', '2015.1', '2015.2', '2016', '2016.1', '2016.2', '2017', '2017.1', '2017.2', '2018', '2018.1', '2018.2', '2019', '2019.1', '2019.2', '2020', '2020.1', '2020.2', '2021', '2021.1', '2021.2']

# 서울(봄,여름,가을,겨울) 데이터 프레임으로 만들기, csv저장

In [258]:
# seoul에서 spring배열에 있는 값만 추출하여 데이터프레임 생성 try except문으로 에러가 나는 부분은 pass
seoul_spring= pd.DataFrame()
for i in range(len(spring)):
    try:
        seoul_spring[spring[i]]= seoul[spring[i]]
    except:
        pass

# 위에코드 함수로 만들기 globals()
def make_df(city, season, s_list):
    globals()[city+"_"+season]= pd.DataFrame()
    for i in range(len(s_list)):
        try:
            globals()[city+"_"+season][s_list[i]]= globals()[city][s_list[i]]
        except:
            pass

# city_list 배열과 season 배열을 이용하여 함수 실행
for i in range(len(city_list)):
    for j in range(len(season)):
        make_df(city_list[i], season[j], season_list[j])

# seoul_spring 데이터프레임 확인
seoul_spring

,2000,2000.1,2000.2,2001,2001.1,2001.2,2002,2002.1,2002.2,2003,...,2018.2,2019,2019.1,2019.2,2020,2020.1,2020.2,2021,2021.1,2021.2
0,일반봄배추:면적 (ha),10a당 생산량 (kg),생산량 (톤),일반봄배추:면적 (ha),10a당 생산량 (kg),생산량 (톤),일반봄배추:면적 (ha),10a당 생산량 (kg),생산량 (톤),일반봄배추:면적 (ha),...,생산량 (톤),일반봄배추:면적 (ha),10a당 생산량 (kg),생산량 (톤),일반봄배추:면적 (ha),10a당 생산량 (kg),생산량 (톤),일반봄배추:면적 (ha),10a당 생산량 (kg),생산량 (톤)
1,72,3695,2660,8,4415,353,49,3313,1623,40,...,1,0,4704,1,0,4661,1,5,4663,228

In [259]:
# csv파일로 저장    
for i in range(len(city_list)):
    for j in range(len(season)):
        globals()[city_list[i]+"_"+season[j]].to_csv("data/"+city_list[i]+"_"+season[j]+".csv", encoding="utf-8", index=False)